import Image from 'next/image';
import Head from 'next/head';
import Markdown from 'markdown-to-jsx';
import { getAllSlugs, getPostData } from '@/lib/posts';
import { Post } from '@/models/post.model';

export async function getStaticPaths(): Promise<{
  paths: {
    params: {
      slug: string;
    };
  }[];
  fallback: boolean;
}> {
  const paths = getAllSlugs();
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }: any): Promise<{
  props: {
    postData: Post;
  };
}> {
  const postData = await getPostData(params.slug);
  return {
    props: {
      postData,
    },
  };
}

type SinglePostProps = {
  postData: Post;
};

export default function SinglePost({ postData }: SinglePostProps): JSX.Element {
  const { contentHtml, date, excerpt, image, title } = postData;
  const formattedDate = new Date(date).toLocaleDateString('en-US', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-4xl pt-[75px]">
        <div className="relative mx-auto h-[200px] w-[200px]">
          <Image
            src={image}
            alt={title}
            fill
            className="rounded-full object-cover"
          />
        </div>
        <h1 className="text-center text-4xl font-bold">{title}</h1>
        <p className="text-center text-lg">{excerpt}</p>
        <address className="text-center text-gray-500">{formattedDate}</address>
        <Markdown
          className="prose mx-auto max-w-4xl"
          options={{
            overrides: {
              img: {
                component: Image,
                props: {
                  width: 300,
                  height: 300,
                  className: 'rounded-xl mx-auto',
                },
              },
            },
          }}
        >
          {contentHtml}
        </Markdown>
      </div>
    </>
  );
}
