import Head from 'next/head';
import PostsGrid from '@/components/posts/PostsGrid';
import getSortedPostData from '@/lib/posts';
import { Post } from '@/models/post.model';

export async function getStaticProps(): Promise<{
  props: {
    allPostsData: Post[];
  };
}> {
  const allPostsData = getSortedPostData();
  return {
    props: {
      allPostsData,
    },
  };
}

type PostsPageProps = {
  allPostsData: Post[];
};

export default function PostsPage({
  allPostsData,
}: PostsPageProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-4xl pt-[75px]">
        <h1 className="py-10 text-center text-4xl font-bold">All Posts</h1>
        <PostsGrid posts={allPostsData} />
      </div>
    </>
  );
}
